name: john-snow
channels:
  - conda-forge
dependencies:
- python=3
- pysal=2.0
- numpy=1.19
- seaborn=0.11
- pandas=1.1
- geopandas=0.8
- matplotlib=3.3
- mapclassify=2.4
- dill=0.3
- notebook=6.1



